### ISSUE TITLE
Question regarding HTML formatting

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/tinytable#83] opened 2024-01-19 13:13 UTC
I'm playing a bit around with the tinytables packages, which really looks cool! But I stumbled upon some issue I cannot resolve, maybe the solution is easy, or maybe this could be a feature request or bug fix...

```r
library(tinytable)
library(ggeffects)
library(datawizard)

data(efc, package = "ggeffects")
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
pr <- ggpredict(fit, terms = c("c12hour [5,15,50,80]", "c172code"))

x <- ggpredict(fit, terms = c("c12hour [5,15,50,80]", "c172code", "c161sex"))
x_label <- attributes(x)$x.title
predicted_label <- attributes(x)$title

has_groups <- ggeffects:::.obj_has_name(x, "group") && length(unique(x$group)) > 1
has_facets <- ggeffects:::.obj_has_name(x, "facet") && length(unique(x$facet)) > 1
has_panel <- ggeffects:::.obj_has_name(x, "panel") && length(unique(x$panel)) > 1
has_response <- ggeffects:::.obj_has_name(x, "response.level") && length(unique(x$response.level)) > 1

sort_columns <- c("response.level", "group", "facet", "panel")[c(has_response, has_groups, has_facets, has_panel)]
x <- datawizard::data_arrange(x, sort_columns)

x$CI <- 0.95
colnames(x)[colnames(x) == "conf.low"] <- "CI_low"
colnames(x)[colnames(x) == "conf.high"] <- "CI_high"

x$x <- insight::format_value(x$x, protect_integers = TRUE)
x <- insight::format_table(x, zap_small = TRUE, ci_brackets = c("(", ")"))

x$std.error <- NULL

row_header_pos <- which(!duplicated(x[sort_columns]))
row_header_labels <- apply(x[row_header_pos, sort_columns], 1, paste, collapse = "<br>")
row_header_labels <- as.list(stats::setNames(row_header_pos, as.vector(row_header_labels)))
x[sort_columns] <- NULL

colnames(x)[1] <- x_label
colnames(x)[2] <- predicted_label

tt(x, output = "html") |>
  style_tt(j = 1:3, align = "llc") |>
  group_tt(i = row_header_labels)
```

I usually use vscode, this example is from RStudio - I wanted to see if the behaviour is different regarding the HTML output/viewer, but apparently it's not. See this screenshot:

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/4e5b4a7f-f5b3-48eb-9c78-76f7fbb68def)

First, how can I include a line break? The vignette says, I have to add `"<br>"` into the related string, what I did: `apply(x[row_header_pos, sort_columns], 1, paste, collapse = "<br>")` - but it doesn't seem to affect row headers? Could you also make this work for rowheaders?

Second, each data row spans over 2 table rows, due to the line break in the "CI" column - based on what I see, I would expect to have enough space that the line break in the CI column is not necessary.

Third, when I explicitly set the width, it seems that the column alignment gets lost? See again the CI column:

```r
tt(x, output = "html", width = 0.9) |>
  style_tt(j = 1:3, align = "llc") |>
  group_tt(i = row_header_labels)
```

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/c5c61399-f3a7-4722-87cc-2ba67cb05b97)

**Comment by vincentarelbundock** [comment] 2024-01-19 15:12
Thanks for trying out the package!

It's a really busy week, but I'll take a look at this as soon as I find some time.

Note that I just pushed commit with some breaking change: we no longer need the `output` argument in `tt()`: https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html#output-formats

**Comment by vincentarelbundock** [comment] 2024-01-19 20:26
The line break should now work with the latest commit from Github dev version. For reference: I substituted `innerText` by `innerHTML` in the javascript.

I think the confidence intervals on different lines is just a zooming issue. Try to zoom out.

I think the alignment of the body is fine: llc. However, the headers do not get styled, so the "95%CI" appears to the extreme left of the last column, which makes it look weird. This is a duplicate of https://github.com/vincentarelbundock/tinytable/issues/34

**Comment by strengejacke** [comment] 2024-01-19 23:02
> I think the confidence intervals on different lines is just a zooming issue. Try to zoom out.

But then it's strange that line break happens for the larger width, while decreasing the width to 0.9 shows CI in one line?

**Comment by vincentarelbundock** [comment] 2024-01-20 00:40
No, by default `width` is left unspecified completely. `tinytable` sets no property at all.

On my computer, if I set `width=1` explicitly, I get *very* similar result to when I set `width=.9`. Also, when I click on "Zoom" to open the table in a separate window and resize, everything is fine.

**Comment by vincentarelbundock** [comment] 2024-01-20 22:48
I'll close this because I really do think that this is about the stylesheet that Rstudio applies, and that there is nothing I can do.

But feel free to keep commenting if you find evidence that this is wrong or have ideas about how I can circumvent the problem. 

FWIW, when I open the HTML in a "real" browser, I don't have any problem with display. CIs are side by side.

**Closed by vincentarelbundock** 2024-01-20 22:48 UTC
