### ISSUE TITLE
tabularray_outer = "long" still prints entire table on next page in PDF

### ISSUE THREAD

**Issue by timnehls** [vincentarelbundock/tinytable#107] opened 2024-01-26 00:49 UTC
I'm really sorry to open an issue again. I use this code
```
df %>%
  tt(width = 1) %>% 
  format_tt(digits = 2, num_fmt = "decimal") %>% 
  style_tt(j = 2, width = "5cm") %>% 
  style_tt(tabularray_outer = "long")
```
to get a long table that starts on the first and that continues on the next page. However, the whole table is on the next page when knitted to a PDF. I tried to remove text that could hinder the table from being partly printed on the first page, but it didn't help. Am I just overlooking something? Thanks in advance!

**Comment by vincentarelbundock** [comment] 2024-01-26 01:30
Honestly, I haven't had time to look into `longtblr` yet. There's another issue open about it, and people have expressed interest (ex @turbanisch )

One guess --- which I have not tested --- is that we currently wrap all LaTeX tables in a floating `table` environment. I don't think we're supposed to do that for long tables, so it may break things. If I were you, I'd try deleting the begin/end lines from the intermediary .tex file, and see what things look like from there.

Eventually, we'll probably want to allow users to specify the latex "flavor" they want, possibly in the "theme" argument. And longtblr should be one option.

**Comment by vincentarelbundock** [comment] 2024-01-26 01:32
BTW, what I'm describing above should be very easy to implement, so while I can't promise anything concrete, I'm not talking about a super long time horizon either.

**Comment by timnehls** [comment] 2024-01-26 01:37
Thanks for your answer. Will try tomorrow.

**Comment by timnehls** [comment] 2024-01-26 10:20
> One guess --- which I have not tested --- is that we currently wrap all LaTeX tables in a floating `table` environment. I don't think we're supposed to do that for long tables, so it may break things. If I were you, I'd try deleting the begin/end lines from the intermediary .tex file, and see what things look like from there.

That indeed works. Thanks a lot.

**Comment by vincentarelbundock** [comment] 2024-01-29 02:50
Glad it worked!

Closing as duplicate of https://github.com/vincentarelbundock/tinytable/issues/13

There will be a clean solution available in the short term.

**Closed by vincentarelbundock** 2024-01-29 02:50 UTC
