### ISSUE TITLE
Inconsistent alignement

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#92] opened 2024-01-20 15:25 UTC
There is an issue with alignement which is inconsistent between HTML and PDF. The table header in html doesn't align right.

HTML:
<img width="400" alt="html_example" src="https://github.com/vincentarelbundock/tinytable/assets/380861/f669a595-c695-4948-b7b2-3aa7c3962bd3">

PDF:
<img width="400" alt="pdf_example" src="https://github.com/vincentarelbundock/tinytable/assets/380861/f68e6ff2-63ea-46ec-a714-04f726cb6a62">

Here's a Quarto reprex for this issue:
````md
---
title: "Alignement test"
format:
  html: default
  pdf: default
---

```{r}
#| echo: false

tibble::tribble(
  ~Column1, ~Column2,
  "Some text", "Some text",
  "123", "456"
) |> 
  tinytable::tt(width = 1) |> 
  tinytable::style_tt(j = 2, align = "r")
```
````

**Comment by vincentarelbundock** [comment] 2024-01-20 16:51
Yes. Headers are not styled at all in HTML right now, and this is a high priority issue.

Closing as duplicate of https://github.com/vincentarelbundock/tinytable/issues/34

**Closed** 2024-01-20 16:51 UTC

**Comment by vincentarelbundock** [comment] 2024-01-20 22:45
@Nenuial this should now be fixed on github

**Comment by Nenuial** [comment] 2024-01-21 01:49
It works as expected. Thanks!
