### ISSUE TITLE
`LaTeX Error: \caption outside float` when saving a table with caption to PDF

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/tinytable#224] opened 2024-04-05 09:07 UTC
``` r
library(tinytable)
library(tinytex)

packageVersion("tinytable")
#> [1] '0.2.1.4'
tinytex::tlmgr_version()
#> tlmgr revision 70671 (2024-03-17 02:10:09 +0100)
#> tlmgr using installation: C:/Users/etienne/AppData/Roaming/TinyTeX
#> TeX Live (https://tug.org/texlive) version 2024

dest <- tempfile(fileext = ".pdf")

### No caption works fine

tt(mtcars) |> 
  save_tt(dest)

### Adding a caption errors

tt(mtcars, caption = "foo") |> 
  save_tt(dest, overwrite = TRUE)
#> ! LaTeX Error: \caption outside float.
#> Error: LaTeX failed to compile idix9jyl0ekzcvee9gaisf.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See idix9jyl0ekzcvee9gaisf.log for more info.
```

**Comment by vincentarelbundock** [comment] 2024-04-05 11:29
Thanks for the report.

The root of the issue is that we use the `standalone` LaTeX package to save a cropped table to file, but that package does not easily seem to accommodate floats with captions.

I need to do an overhaul of captions for all formats (see https://github.com/vincentarelbundock/tinytable/issues/208), but it might take me a little while.

**Comment by vincentarelbundock** [comment] 2024-04-14 02:26
Thanks again for the report. Should be fixed on Github. This code:

```r
library(tinytable)
x <- mtcars[1:5, 1:5]
tt(x, caption = "A simple table with caption.", width = .6) |>
    save_tt("example.pdf", overwrite = TRUE)
```

Generates this file:

[example.pdf](https://github.com/vincentarelbundock/tinytable/files/14969276/example.pdf)

**Closed by vincentarelbundock** 2024-04-14 02:26 UTC
