### ISSUE TITLE
group_tt( j = ...) shifts last row of data to left

### ISSUE THREAD

**Issue by docfleetwood** [vincentarelbundock/tinytable#58] opened 2024-01-14 17:24 UTC
When I run the code below, the final row seems to shift to being left aligned. It happens when I add the group_tt() function with j=. If I remove that function, the alignment remains correct. I have reproduced this with several datasets, but this is the simplest example.

```r
tt(iris[1:10,], align = "ccccc") %>% 
  group_tt(
    j = list("Sepal" = 1:2,
             "Petal" = 3:4)
```

**Comment by docfleetwood** [comment] 2024-01-14 17:26
Thank you for the package. The simplicity of this package makes it very intriguing.

**Comment by vincentarelbundock** [comment] 2024-01-15 04:29
Thanks a lot for the report, and for making the effort to find a truly minimal example. Super useful!

I can replicate the problem on my computer. I think it's a simple indexing issue and should be reasonably easy to fix. I'll let you know when it's done.

**Comment by vincentarelbundock** [comment] 2024-01-15 16:58
Note to self: This does not affect LaTeX. The problem is that stylings in HTML is done row by row, even for column styles like alignment. In this case, we style when calling `tt()`, but then add a new row with the header, so that pushes things down. The last row is not styled, and thus not centered, which makes it look as if it was shifted to the left.

The "cleanest" solution would be to remove `align` from `tt()` and to put it in `style_tt()`. That really is a styling option, and it fits better there "conceptually". It is convenient to have it in `tt()`, but maybe we have to bite the bullet here for consistency and robustness.

**Comment by vincentarelbundock** [comment] 2024-01-17 03:51
Thanks again. This should be fixed in the Github version (make sure you restart R after install).

![image](https://github.com/vincentarelbundock/tinytable/assets/987057/586fe704-a2e3-46b8-9b95-6dcfdfe49c34)

**Closed by vincentarelbundock** 2024-01-17 03:51 UTC

**Comment by docfleetwood** [comment] 2024-01-17 18:32
Thanks, works on multiple tables of different complexity I have created. I probably agree with your idea of moving it to style-tt() for consistency of application.

**Comment by vincentarelbundock** [comment] 2024-01-17 19:53
Great to hear, thanks for checking!
